name:                day1
version:             0.1.0.0
github:              "ozkutuk/aoc20"
license:             BSD3
author:              "Berk Ozkutuk <ozkutuk.berk@gmail.com>"

dependencies:
- base >= 4.7 && < 5
- text

default-extensions:
- OverloadedStrings

executables:
  day1:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
