name:                day4
version:             0.1.0.0
github:              "ozkutuk/aoc20"
license:             MIT
author:              "Berk Ozkutuk <ozkutuk.berk@gmail.com>"

dependencies:
- base >= 4.7 && < 5
- text
- unordered-containers >= 0.2.12
- megaparsec
- hashable

default-extensions:
- OverloadedStrings
- LambdaCase

executables:
  day4:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
